Desktop version
Athaliah8/Mobile_Portfolio pull request #3
Opened 2022-11-10 19:39 UTC by Athaliah8

##In This repo
[ ]Added media queries 
[ ]Added addition html elements

2022-11-10 20:35 UTC, andgarzonmal requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 Hi @Athaliah8    ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them and your project will be approved.

___ 

### 💯  Highlights 💯
- Your gitHub flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️

### ♻️ Request changes ♻️

- [x] _Check the comments under the review._
___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-10 20:35 UTC, andgarzonmal commented on index.html
>            </nav>
- [ ]  Kyndly stick to the figma template as much as you can,  please notice that in the figma template the navbar does not take the 100% of the width of the page, there are some spaces on the right and left side of the navbar. ✏️

Your design 

![image](https://user-images.githubusercontent.com/95243996/201193584-472d47aa-6da7-487f-8d7f-837f24e5dd19.png)

Figma template

![image](https://user-images.githubusercontent.com/95243996/201193995-4f66a2db-0dbb-49a2-97fb-4f4df308a923.png)

2022-11-10 20:35 UTC, andgarzonmal commented on index.html
> +
- [ ]  Kyndly stick to the figma design as much as posible, in the cards section you added too much margin to the left and rigt side of the cards in comparison to the figma design.

## Figma design 

![image](https://user-images.githubusercontent.com/95243996/201197659-279838ca-55cb-4b8b-949f-423e2aecad5b.png)

## Your design

![image](https://user-images.githubusercontent.com/95243996/201197817-e5919336-d89e-4470-bc9d-03d3970dd2d3.png)

2022-11-10 20:35 UTC, andgarzonmal commented on index.html
> +
- [ ]  Kyndly stick to the figma design as much as posible, in the cards section you have to place the card images according to the figma design, please notice that in some cards the image is on the right side and in others the image is on the left side.

## Figma design
![image](https://user-images.githubusercontent.com/95243996/201198370-71ea6965-b9d1-4b5d-beb6-f78b8a7fbf75.png)

## Your design 

![image](https://user-images.githubusercontent.com/95243996/201198844-9dfd5f22-7c3b-4fed-9c83-09500fdb1351.png)

2022-11-10 20:35 UTC, andgarzonmal commented on index.html
> +              </div>
- [ ]  Kyndly stick to the figma design as much as posible please notice you have several diferences in the About myself section .

## Your design 
![image](https://user-images.githubusercontent.com/95243996/201199537-43017528-be50-4938-968a-00cd415e403f.png)

## Figma design 

![image](https://user-images.githubusercontent.com/95243996/201199418-a5acc49b-b57e-4043-b3c1-e2b205381835.png)

2022-11-10 20:35 UTC, andgarzonmal commented on index.html
> +
Kyndly stick to the figma design as much as posible, please notice in the contact form the form does not take to much with of the page.

## Figma design 
![image](https://user-images.githubusercontent.com/95243996/201200324-4905c75c-9706-4c3b-9b9c-165c821cbd36.png)

## Your design
![image](https://user-images.githubusercontent.com/95243996/201200462-bce73bfa-6955-4e7e-8c43-80f2006042ce.png)

2022-11-11 05:42 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️   

## Hi @Athaliah8 👋,

You've done well implementing some of the requested changes 👏 , but there are still some which haven't been addressed yet.

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Implemented some of the changes requested by the previous reviewer.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 05:42 UTC, Gopxfs commented on style.css
> +}
As requested by the previous reviewer, kindly make sure that your `nav` element doesn't occupy the whole width 😄:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/201269126-6adbed89-cfe6-4c4d-86d2-d32f7e7dd682.png)  | ![image](https://user-images.githubusercontent.com/42799579/201269076-bf99ebb3-0aed-4845-a03f-ad144fb93583.png)  |

Check the space between the elements and the body border in the original design 😉.

> Note: you can always click on the images to see them with more details.

2022-11-11 05:42 UTC, Gopxfs commented on index.html
> +
As requested by the previous reviewer, kindly update the margin on your projects section. Currently, there is too much space between the card and the body border 😉.

| Figma design  | Your design |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/95243996/201197659-279838ca-55cb-4b8b-949f-423e2aecad5b.png"/>  | <img src="https://user-images.githubusercontent.com/95243996/201197817-e5919336-d89e-4470-bc9d-03d3970dd2d3.png" />  |

> Keep in mind that this project's goal is to improve your ability to follow design guidelines (imagine Microverse as a client requesting a website) 😉.

2022-11-11 05:42 UTC, Gopxfs commented on index.html
>                        <p class="title">CANOPY</p>
As requested by the previous reviewer, kindly make sure to make your project's images intersect between left and right, as displayed below 😉:

| Figma design  | Your design |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/95243996/201197659-279838ca-55cb-4b8b-949f-423e2aecad5b.png"/>  | <img src="https://user-images.githubusercontent.com/95243996/201198844-9dfd5f22-7c3b-4fed-9c83-09500fdb1351.png" />  |

2022-11-11 05:42 UTC, Gopxfs commented on style.css
>  }
As requested by the previous reviewer, please make sure to apply the desktop design displayed on Figma 😉. Please note that, currently, you still have your mobile version styling:

| Figma design  | Your design |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/95243996/201199537-43017528-be50-4938-968a-00cd415e403f.png" />  | <img src="https://user-images.githubusercontent.com/95243996/201199418-a5acc49b-b57e-4043-b3c1-e2b205381835.png" />  |

2022-11-11 07:05 UTC, merged